# Win/Loss ratio's correlation

For each sport, we will find the win/loss ratio's correlation with the population of the city it is in. Win/Loss ratio refers to the number of wins over the number of wins plus the number of losses. We will calculate the correlation with pearsonr using the population data obtained from the wikipedia_data.html file and the win/loss ratio for a given sport.

In [3]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("mlb.csv")
nhl_df=pd.read_csv("nhl.csv")
nba_df=pd.read_csv("nba.csv")
nfl_df=pd.read_csv("nfl.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

In [6]:
mlb_df.head(10)

                 team    W    L   W-L%    GB  year League
0      Boston Red Sox  108   54  0.667    --  2018    MLB
1    New York Yankees  100   62  0.617   8.0  2018    MLB
2      Tampa Bay Rays   90   72  0.556  18.0  2018    MLB
3   Toronto Blue Jays   73   89  0.451  35.0  2018    MLB
4   Baltimore Orioles   47  115  0.290  61.0  2018    MLB
5   Cleveland Indians   91   71  0.562    --  2018    MLB
6     Minnesota Twins   78   84  0.481  13.0  2018    MLB
7      Detroit Tigers   64   98  0.395  27.0  2018    MLB
8   Chicago White Sox   62  100  0.383  29.0  2018    MLB
9  Kansas City Royals   58  104  0.358  33.0  2018    MLB

In [7]:
nhl_df.head(10)

,team,GP,W,L,OL,PTS,PTS%,GF,GA,SRS,SOS,RPt%,ROW,year,League
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,2018,NHL
1,Tampa Bay Lightning*,82,54,23,5,113,.689,296,236,0.66,-0.07,.634,48,2018,NHL
2,Boston Bruins*,82,50,20,12,112,.683,270,214,0.62,-0.07,.610,47,2018,NHL
3,Toronto Maple Leafs*,82,49,26,7,105,.640,277,232,0.49,-0.06,.567,42,2018,NHL
4,Florida Panthers,82,44,30,8,96,.585,248,246,-0.01,-0.04,.537,41,2018,NHL
5,Detroit Red Wings,82,30,39,13,73,.445,217,255,-0.48,-0.01,.341,25,2018,NHL
6,Montreal Canadiens,82,29,40,13,71,.433,209,264,-0.68,0.00,.378,27,2018,NHL
7,Ottawa Senators,82,28,43,11,67,.409,221,291,-0.85,0.00,.372,26,2018,NHL
8,Buffalo Sabres,82,25,45,12,62,.378,199,280,-0.98,0.01,.311,24,2018,NHL
9,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,2018,NHL

In [8]:
nba_df.head(10)

,team,W,L,W/L%,GB,PS/G,PA/G,SRS,year,League
0,Toronto Raptors* (1),59,23,0.72,—,111.7,103.9,7.29,2018,NBA
1,Boston Celtics* (2),55,27,0.6709999999999999,4.0,104.0,100.4,3.23,2018,NBA
2,Philadelphia 76ers* (3),52,30,0.634,7.0,109.8,105.3,4.3,2018,NBA
3,Cleveland Cavaliers* (4),50,32,0.61,9.0,110.9,109.9,0.59,2018,NBA
4,Indiana Pacers* (5),48,34,0.585,11.0,105.6,104.2,1.18,2018,NBA
5,Miami Heat* (6),44,38,0.537,15.0,103.4,102.9,0.15,2018,NBA
6,Milwaukee Bucks* (7),44,38,0.537,15.0,106.5,106.8,-0.45,2018,NBA
7,Washington Wizards* (8),43,39,0.524,16.0,106.6,106.0,0.53,2018,NBA
8,Detroit Pistons (9),39,43,0.47600000000000003,20.0,103.8,103.9,-0.26,2018,NBA
9,Charlotte Hornets (10),36,46,0.439,23.0,108.2,108.0,0.07,2018,NBA

In [9]:
nfl_df

,DSRS,L,League,MoV,OSRS,PA,PD,PF,SRS,SoS,T,W,W-L%,team,year
0,AFC East,AFC East,NFL,AFC East,AFC East,AFC East,AFC East,AFC East,AFC East,AFC East,AFC East,AFC East,AFC East,AFC East,2018
1,2.1,5,NFL,6.9,3.1,325,111,436,5.2,-1.8,0,11,.688,New England Patriots*,2018
2,-5.2,9,NFL,-7.1,-3.6,433,-114,319,-8.8,-1.7,0,7,.438,Miami Dolphins,2018
3,-0.6,10,NFL,-6.6,-6.3,374,-105,269,-6.9,-0.3,0,6,.375,Buffalo Bills,2018
4,-5.9,12,NFL,-6.8,-2.0,441,-108,333,-7.8,-1.1,0,4,.250,New York Jets,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,NFC West,NFC West,NFL,NFC West,NFC West,NFC West,NFC West,NFC West,NFC West,NFC West,NFC West,NFC West,NFC West,NFC West,2014
196,7.1,4,NFL,8.8,2.4,254,140,394,9.5,0.8,0,12,.750,Seattle Seahawks*,2014
197,4.4,5,NFL,0.7,-2.4,299,11,310,2.0,1.3,0,11,.688,Arizona Cardinals+,2014
198,2.1,8,NFL,-2.1,-3.0,340,-34,306,-1.0,1.2,0,8,.500,San Francisco 49ers,2014
199,0.4,10,NFL,-1.9,-1.2,354,-30,324,-0.8,1.0,0,6,.375,St. Louis Rams,2014

##  NHL
The win/loss ratio's correlation with the population of the city it is in for the NHL using 2018 data.

In [10]:
def nhl_helper():
    cities_copy = cities[['Metropolitan area', 'Population (2016 est.)[8]', 'NHL']].copy()
    cities_copy['NHL'] = cities_copy['NHL'].replace('\[.*\]|—', '', regex=True)
    cities_copy = cities_copy[cities_copy['NHL'].astype(bool)]
    
    nyc_teams = cities_copy.iloc[0]['NHL']
    nyc_teams = re.findall('[A-Z][a-z]+', nyc_teams)
    la_teams = cities_copy.loc[1]['NHL']
    la_teams = re.findall('[A-Z][a-z]+', la_teams)

    for team in nyc_teams:
        t = cities_copy.iloc[0].copy()
        t['NHL'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)
    for team in la_teams:
        t = cities_copy.iloc[1].copy()
        t['NHL'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)

    cities_copy = cities_copy.drop([0,1])
    
    nhl_df_copy = nhl_df[nhl_df['year'] == 2018].copy()
    nhl_df_copy[['W', 'L']] = nhl_df_copy[['W', 'L']].replace('[a-zA-Z]+', np.nan, regex=True)
    nhl_df_copy.dropna(inplace=True)
    nhl_df_copy.index = range(len(nhl_df_copy.index))
    nhl_df_copy[['W', 'L']] = nhl_df_copy[['W', 'L']].astype(int)
    nhl_df_copy['win_loss_ratio'] = nhl_df_copy['W'] / (nhl_df_copy['W'] + nhl_df_copy['L'])
    
    
    def w_l_ratio(x):
        teams = list(nhl_df_copy['team'])
        for i in range(len(teams)):
            if x in teams[i]:
                return nhl_df_copy.iloc[i]['win_loss_ratio']
    
    cities_copy['win_loss_ratio'] = cities_copy['NHL'].apply(lambda x : w_l_ratio(x))
    cities_copy['Population (2016 est.)[8]'] = cities_copy['Population (2016 est.)[8]'].astype(int)
    cities_copy = cities_copy.groupby('Metropolitan area').agg({'Population (2016 est.)[8]': np.mean,'win_loss_ratio': np.mean})
    cities_copy.rename(columns={'Population (2016 est.)[8]': 'Population'}, inplace=True)
    
    return cities_copy

def nhl_correlation():     
    cities_copy = nhl_helper()
    
    population_by_region = cities_copy['Population'] 
    win_loss_by_region = cities_copy['win_loss_ratio']

    return stats.pearsonr(population_by_region, win_loss_by_region)[0]

nhl_correlation()

0.012486162921209909

##  NBA
The win/loss ratio's correlation with the population of the city it is in for the NBA using 2018 data.

In [13]:
def nba_helper():
    cities_copy = cities[['Metropolitan area', 'Population (2016 est.)[8]', 'NBA']].copy()
    cities_copy['NBA'] = cities_copy['NBA'].replace('\[.*\]|—', '', regex=True)
    cities_copy = cities_copy[cities_copy['NBA'].astype(bool)]
    
    nyc_teams = cities_copy.iloc[0]['NBA']
    nyc_teams = re.findall('[A-Z][a-z]+', nyc_teams)
    la_teams = cities_copy.loc[1]['NBA']
    la_teams = re.findall('[A-Z][a-z]+', la_teams)

    for team in nyc_teams:
        t = cities_copy.iloc[0].copy()
        t['NBA'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)
    for team in la_teams:
        t = cities_copy.iloc[1].copy()
        t['NBA'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)
   
    cities_copy = cities_copy.drop([0,1])
    
    nba_df_copy = nba_df[nba_df['year'] == 2018].copy()
    nba_df_copy[['W', 'L']] = nba_df_copy[['W', 'L']].replace('[a-zA-Z]+', np.nan, regex=True)
    nba_df_copy.dropna(inplace=True)
    nba_df_copy.index = range(len(nba_df_copy.index))
    nba_df_copy[['W', 'L']] = nba_df_copy[['W', 'L']].astype(int)
    nba_df_copy['win_loss_ratio'] = nba_df_copy['W'] / (nba_df_copy['W'] + nba_df_copy['L'])
    
    def w_l_ratio(x):
        teams = list(nba_df_copy['team'])
        for i in range(len(teams)):
            if x in teams[i]:
                return nba_df_copy.iloc[i]['win_loss_ratio']
    
    cities_copy['win_loss_ratio'] = cities_copy['NBA'].apply(lambda x : w_l_ratio(x))
    cities_copy['Population (2016 est.)[8]'] = cities_copy['Population (2016 est.)[8]'].astype(int)
    cities_copy = cities_copy.groupby('Metropolitan area').agg({'Population (2016 est.)[8]': np.mean,'win_loss_ratio': np.mean})
    cities_copy.rename(columns={'Population (2016 est.)[8]': 'Population'}, inplace=True)
    
    return cities_copy


def nba_correlation():
    cities_copy = nba_helper()
    
    population_by_region = cities_copy['Population'] 
    win_loss_by_region = cities_copy['win_loss_ratio'] 
    
    return stats.pearsonr(population_by_region, win_loss_by_region)[0]

nba_correlation()

-0.17657160252844611

##  MLB
The win/loss ratio's correlation with the population of the city it is in for the MLB using 2018 data.

In [15]:
def mlb_helper():
    cities_copy = cities[['Metropolitan area', 'Population (2016 est.)[8]', 'MLB']].copy()
    cities_copy['MLB'] = cities_copy['MLB'].replace('\[.*\]|—', '', regex=True)
    cities_copy = cities_copy[cities_copy['MLB'].astype(bool)]
    
    nyc_teams = cities_copy.iloc[0]['MLB']
    nyc_teams = re.findall('[A-Z][a-z]+', nyc_teams)
    la_teams = cities_copy.loc[1]['MLB']
    la_teams = re.findall('[A-Z][a-z]+', la_teams)
    sf_teams = cities_copy.loc[2]['MLB']
    sf_teams = re.findall('[A-Z][a-z]+', sf_teams)
    chicago_teams = cities_copy.loc[3]['MLB']
    chicago_teams = re.findall('[A-Z][a-z]+\s\w*|[A-Z][a-z]+', chicago_teams)

    for team in nyc_teams:
        t = cities_copy.iloc[0].copy()
        t['MLB'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)
    for team in la_teams:
        t = cities_copy.iloc[1].copy()
        t['MLB'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)
    for team in sf_teams:
        t = cities_copy.iloc[2].copy()
        t['MLB'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)
    for team in chicago_teams:
        t = cities_copy.iloc[3].copy()
        t['MLB'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)
   
    cities_copy = cities_copy.drop([0,1,2,3])
    
    mlb_df_copy = mlb_df[mlb_df['year'] == 2018].copy()
    mlb_df_copy[['W', 'L']] = mlb_df_copy[['W', 'L']].astype(int)
    mlb_df_copy['win_loss_ratio'] = mlb_df_copy['W'] / (mlb_df_copy['W'] + mlb_df_copy['L'])
    
    def w_l_ratio(x):
        teams = list(mlb_df_copy['team'])
        for i in range(len(teams)):
            if x in teams[i]:
                return mlb_df_copy.iloc[i]['win_loss_ratio']
    
    cities_copy['win_loss_ratio'] = cities_copy['MLB'].apply(lambda x : w_l_ratio(x))
    cities_copy['Population (2016 est.)[8]'] = cities_copy['Population (2016 est.)[8]'].astype(int)
    cities_copy = cities_copy.groupby('Metropolitan area').agg({'Population (2016 est.)[8]': np.mean,'win_loss_ratio': np.mean})
    cities_copy.rename(columns={'Population (2016 est.)[8]': 'Population'}, inplace=True)
    
    return cities_copy


def mlb_correlation():   
    cities_copy = mlb_helper()
    
    population_by_region = cities_copy['Population']
    win_loss_by_region = cities_copy['win_loss_ratio']

    return stats.pearsonr(population_by_region, win_loss_by_region)[0]

mlb_correlation()

0.1502769830266931

##  NFL
The win/loss ratio's correlation with the population of the city it is in for the NFL using 2018 data.

In [17]:
def nfl_helper():
    cities_copy = cities[['Metropolitan area', 'Population (2016 est.)[8]', 'NFL']].copy()
    cities_copy['NFL'] = cities_copy['NFL'].replace('\[.*\]|— |—', '', regex=True)
    cities_copy = cities_copy[cities_copy['NFL'].astype(bool)]
    
    nyc_teams = cities_copy.iloc[0]['NFL']
    nyc_teams = re.findall('[A-Z][a-z]+', nyc_teams)
    la_teams = cities_copy.loc[1]['NFL']
    la_teams = re.findall('[A-Z][a-z]+', la_teams)
    sf_teams = cities_copy.loc[2]['NFL']
    sf_teams = re.findall('[A-Z][a-z]+|\d{2}[a-z]+', sf_teams)

    for team in nyc_teams:
        t = cities_copy.iloc[0].copy()
        t['NFL'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)
    for team in la_teams:
        t = cities_copy.iloc[1].copy()
        t['NFL'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)
    for team in sf_teams:
        t = cities_copy.iloc[2].copy()
        t['NFL'] = team
        cities_copy = cities_copy.append(t, ignore_index=True)
   
    cities_copy = cities_copy.drop([0,1,2])
    
    nfl_df_copy = nfl_df[nfl_df['year'] == 2018].copy()
    nfl_df_copy[['W', 'L']] = nfl_df_copy[['W', 'L']].replace('[a-zA-Z]+', np.nan, regex=True)
    nfl_df_copy.dropna(inplace=True)
    nfl_df_copy.index = range(len(nfl_df_copy.index))
    nfl_df_copy[['W', 'L']] = nfl_df_copy[['W', 'L']].astype(int)
    nfl_df_copy['win_loss_ratio'] = nfl_df_copy['W'] / (nfl_df_copy['W'] + nfl_df_copy['L'])
    
    def w_l_ratio(x):
        teams = list(nfl_df_copy['team'])
        for i in range(len(teams)):
            if x in teams[i]:
                return nfl_df_copy.iloc[i]['win_loss_ratio']
    
    cities_copy['win_loss_ratio'] = cities_copy['NFL'].apply(lambda x : w_l_ratio(x))
    cities_copy['Population (2016 est.)[8]'] = cities_copy['Population (2016 est.)[8]'].astype(int)
    cities_copy = cities_copy.groupby('Metropolitan area').agg({'Population (2016 est.)[8]': np.mean,'win_loss_ratio': np.mean})
    cities_copy.rename(columns={'Population (2016 est.)[8]': 'Population'}, inplace=True)
    
    return cities_copy
    

def nfl_correlation():   
    cities_copy = nfl_helper()
    
    population_by_region = cities_copy['Population']
    win_loss_by_region = cities_copy['win_loss_ratio']

    return stats.pearsonr(population_by_region, win_loss_by_region)[0]

nfl_correlation()

0.004922112149349428

## Hypothesis
Given that an area has two sports teams in different sports, we will explore if those teams will perform the same within their respective sports. So we wil explore this idea with a series of paired t-tests between all pairs of sports.

In [18]:
def sports_team_performance():
    mlb_df = mlb_helper()
    mlb_df.name = 'MLB'
    
    nhl_df = nhl_helper()
    nhl_df.name = 'NHL'
    
    nba_df = nba_helper()
    nba_df.name = 'NBA'
    
    nfl_df = nfl_helper()
    nfl_df.name = 'NFL'
    
    sports = ['NFL', 'NBA', 'NHL', 'MLB']
    p_values = pd.DataFrame({k:np.nan for k in sports}, index=sports)

    sports_df = [nfl_df, nba_df, nhl_df, mlb_df]
    for row in sports_df:
        for col in sports_df:
            if row.name == col.name:
                p_values.loc[row.name, col.name] = np.nan
            else:
                df = pd.merge(row, col, how='inner', left_index=True, right_index=True)
                p_val = stats.ttest_rel(df['win_loss_ratio_x'], df['win_loss_ratio_y'])
                p_values.loc[row.name][col.name] = p_val[1]
    
    return p_values

sports_team_performance()

          NFL       NBA       NHL       MLB
NFL       NaN  0.941792  0.030883  0.802069
NBA  0.941792       NaN  0.022297  0.950540
NHL  0.030883  0.022297       NaN  0.000708
MLB  0.802069  0.950540  0.000708       NaN